version: "3.9"

services:
  db:
    image: postgres:15
    container_name: training_tracker_db
    environment:
      POSTGRES_DB: trainingdb
      POSTGRES_USER: traininguser
      POSTGRES_PASSWORD: trainingpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U traininguser -d trainingdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: training_tracker_backend
    environment:
      - POSTGRES_DSN=host=db user=traininguser password=trainingpass dbname=trainingdb port=5432 sslmode=disable TimeZone=UTC
      - GIN_MODE=release
      - PORT=8080
      - CORS_ORIGIN=http://localhost:3001
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: training_tracker_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  db_data:

